# Generated by Django 3.1.5 on 2021-01-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_prdcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image'),
        ),
    ]
