# Generated by Django 3.1.5 on 2021-01-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_prddiscountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDISBastSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISNew',
            field=models.BooleanField(default=True),
        ),
    ]
