# Generated by Django 3.1.5 on 2021-01-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20210107_0730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
